=== elgarcito/solvd-2-block-homework-6/src/main/resources/xsdFiles/essayModuleList.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="essayModuleList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="essayModules" type="essayModulesType"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:long" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="essayModulesType">
        <xs:sequence>
            <xs:element name="essayModule" type="essayModuleType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="essayModuleType">
        <xs:sequence>
            <xs:element name="moduleDescription" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

</xs:schema>

=== elgarcito/solvd-2-block-homework-6/src/main/resources/xmlFiles/essayModuleList.xml
<essayModuleList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="../xsdFiles/essayModuleList.xsd"  id="1">
    <essayModules>

    <essayModule id="1">
        <moduleDescription>"Big module"</moduleDescription>
    </essayModule>
    <essayModule id="2">
        <moduleDescription>"medium module"</moduleDescription>
    </essayModule>
    <essayModule id="3">
        <moduleDescription>"small module"</moduleDescription>
    </essayModule>
    </essayModules>
</essayModuleList>
